import './globals.css'
import { Cabin, Cabin_Sketch } from 'next/font/google'

export const cabin = Cabin({ 
  subsets: ['latin'],
  display: 'swap'
})

export const cabin_sketch = Cabin_Sketch({ 
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap'
})

/* export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} */

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={cabin.className}>{children}</body>
    </html>
  )
}
